### ISSUE TITLE
HP m130 can not work

### ISSUE THREAD

**Issue by laipochen** [LeoKlaus/OpenAirScan#3]
I can see the device in the search list, but when I click on it, I can't adjust all the settings. I think maybe the APP didn't ask eSCL URI 'ScannerCapabilities'?

**Comment by LeoKlaus** [comment]
Hey laipochen, thank you for creating an issue for this!

The ScannerCapabilities URI is checked to determine available features, so you missing some of them is odd.
It would be great if you could provide me with some more information:

- Are all capabilities missing or just some, if so, which?

- Can you curl https://[ip-of-your-scanner]/eSCL/ScannerCapabilities and add the response in a comment here? I think you should also be able to just open that URL in your browser, but I'm not at home right now so I can't check.

**Comment by laipochen** [comment]
Hi LeoKlaus, thank you for your reply.
When I use WireShark to capture packet in MACOS (use "Printer and Scanner" to open Scanner), I can see MACOS to query the URI 'ScannerCapabilities' and 'ScannerStatus'.
But I can't capture packet in my iPhone so I'm not sure which ones are not given.
My device not enable "https" so I just try "http".
I can get the XML response through the browser. Below is the XML response from my device.

`
<scan:ScannerCapabilities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:scan="http://schemas.hp.com/imaging/escl/2011/05/03" xmlns:pwg="http://www.pwg.org/schemas/2010/12/sm" xsi:schemaLocation="http://schemas.hp.com/imaging/escl/2011/05/03 eSCL.xsd">
<pwg:Version>2.5</pwg:Version>
<pwg:MakeAndModel>HP LaserJet MFP M130fw</pwg:MakeAndModel>
<pwg:SerialNumber>********</pwg:SerialNumber>
<scan:Platen>
<scan:PlatenInputCaps>
<scan:MinWidth>576</scan:MinWidth>
<scan:MaxWidth>2550</scan:MaxWidth>
<scan:MinHeight>576</scan:MinHeight>
<scan:MaxHeight>3508</scan:MaxHeight>
<scan:MaxScanRegions>1</scan:MaxScanRegions>
<scan:SettingProfiles>
<scan:SettingProfile>
<scan:ColorModes>
<scan:ColorMode>RGB24</scan:ColorMode>
<scan:ColorMode>Grayscale8</scan:ColorMode>
</scan:ColorModes>
<scan:ContentTypes>
<pwg:ContentType>Photo</pwg:ContentType>
<pwg:ContentType>Text</pwg:ContentType>
<pwg:ContentType>TextAndPhoto</pwg:ContentType>
</scan:ContentTypes>
<scan:DocumentFormats>
<pwg:DocumentFormat>image/jpeg</pwg:DocumentFormat>
<pwg:DocumentFormat>application/pdf</pwg:DocumentFormat>
<scan:DocumentFormatExt>image/jpeg</scan:DocumentFormatExt>
<scan:DocumentFormatExt>application/pdf</scan:DocumentFormatExt>
</scan:DocumentFormats>
<scan:SupportedResolutions>
<scan:DiscreteResolutions>
<scan:DiscreteResolution>
<scan:XResolution>75</scan:XResolution>
<scan:YResolution>75</scan:YResolution>
</scan:DiscreteResolution>
<scan:DiscreteResolution>
<scan:XResolution>200</scan:XResolution>
<scan:YResolution>200</scan:YResolution>
</scan:DiscreteResolution>
<scan:DiscreteResolution>
<scan:XResolution>300</scan:XResolution>
<scan:YResolution>300</scan:YResolution>
</scan:DiscreteResolution>
<scan:DiscreteResolution>
<scan:XResolution>600</scan:XResolution>
<scan:YResolution>600</scan:YResolution>
</scan:DiscreteResolution>
<scan:DiscreteResolution>
<scan:XResolution>1200</scan:XResolution>
<scan:YResolution>1200</scan:YResolution>
</scan:DiscreteResolution>
</scan:DiscreteResolutions>
</scan:SupportedResolutions>
<scan:ColorSpaces>
<scan:ColorSpace>sRGB</scan:ColorSpace>
</scan:ColorSpaces>
</scan:SettingProfile>
</scan:SettingProfiles>
<scan:SupportedIntents>
<scan:Intent>Document</scan:Intent>
<scan:Intent>Photo</scan:Intent>
<scan:Intent>Preview</scan:Intent>
<scan:Intent>TextAndGraphic</scan:Intent>
</scan:SupportedIntents>
<scan:MaxOpticalXResolution>1200</scan:MaxOpticalXResolution>
<scan:MaxOpticalYResolution>1200</scan:MaxOpticalYResolution>
</scan:PlatenInputCaps>
</scan:Platen>
<scan:Adf>
<scan:AdfSimplexInputCaps>
<scan:MinWidth>576</scan:MinWidth>
<scan:MaxWidth>2550</scan:MaxWidth>
<scan:MinHeight>576</scan:MinHeight>
<scan:MaxHeight>4500</scan:MaxHeight>
<scan:MaxScanRegions>1</scan:MaxScanRegions>
<scan:SettingProfiles>
<scan:SettingProfile>
<scan:ColorModes>
<scan:ColorMode>RGB24</scan:ColorMode>
<scan:ColorMode>Grayscale8</scan:ColorMode>
</scan:ColorModes>
<scan:ContentTypes>
<pwg:ContentType>Photo</pwg:ContentType>
<pwg:ContentType>Text</pwg:ContentType>
<pwg:ContentType>TextAndPhoto</pwg:ContentType>
</scan:ContentTypes>
<scan:DocumentFormats>
<pwg:DocumentFormat>image/jpeg</pwg:DocumentFormat>
<pwg:DocumentFormat>application/pdf</pwg:DocumentFormat>
<scan:DocumentFormatExt>image/jpeg</scan:DocumentFormatExt>
<scan:DocumentFormatExt>application/pdf</scan:DocumentFormatExt>
</scan:DocumentFormats>
<scan:SupportedResolutions>
<scan:DiscreteResolutions>
<scan:DiscreteResolution>
<scan:XResolution>75</scan:XResolution>
<scan:YResolution>75</scan:YResolution>
</scan:DiscreteResolution>
<scan:DiscreteResolution>
<scan:XResolution>200</scan:XResolution>
<scan:YResolution>200</scan:YResolution>
</scan:DiscreteResolution>
<scan:DiscreteResolution>
<scan:XResolution>300</scan:XResolution>
<scan:YResolution>300</scan:YResolution>
</scan:DiscreteResolution>
</scan:DiscreteResolutions>
</scan:SupportedResolutions>
<scan:ColorSpaces>
<scan:ColorSpace>sRGB</scan:ColorSpace>
</scan:ColorSpaces>
</scan:SettingProfile>
</scan:SettingProfiles>
<scan:SupportedIntents>
<scan:Intent>Document</scan:Intent>
<scan:Intent>Photo</scan:Intent>
<scan:Intent>Preview</scan:Intent>
<scan:Intent>TextAndGraphic</scan:Intent>
</scan:SupportedIntents>
<scan:MaxOpticalXResolution>300</scan:MaxOpticalXResolution>
<scan:MaxOpticalYResolution>300</scan:MaxOpticalYResolution>
</scan:AdfSimplexInputCaps>
<scan:FeederCapacity>50</scan:FeederCapacity>
<scan:AdfOptions>
<scan:AdfOption>DetectPaperLoaded</scan:AdfOption>
<scan:AdfOption>SelectSinglePage</scan:AdfOption>
</scan:AdfOptions>
</scan:Adf>
<scan:ContrastSupport>
<scan:Min>-127</scan:Min>
<scan:Max>127</scan:Max>
<scan:Normal>0</scan:Normal>
<scan:Step>1</scan:Step>
</scan:ContrastSupport>
</scan:ScannerCapabilities>
`

**Comment by LeoKlaus** [comment]
Thank you for the quick response. The XML looks fine and I don't see why the app would fail to parse it.

> My device not enable "https" so I just try "http".

That is curious. I always assumed eSCL works via https only. Based on that assumption, OpenAirScan _always_ uses https for requests.

Are you able to perform scans at all?

I'll try to fix this later today and report back to you.

**Comment by laipochen** [comment]
After I enable the "https", OpenAirScan APP can work find!
I have do some research and I found the Mopria Scan is used same  eSCL in Android.
And I found a specification in which the description of MDNS has instructions for encrypted connections. [https://mopria.org/mopria-escl-specification](url)  
PTR record _uscan._tcp.local is for http , PTR record _uscans._tcp.local is for https
I suggest that you can use this to make a judgment whether to use https or http.

**Comment by LeoKlaus** [comment]
Hi, sorry for the late response, I've got my hands full with another project right now and didn't find time to continue work on this yet.

Thank you for all the information, it's really helpful and gave me a much better insight in how eSCL works. I hope to implement a better handling for connections in the near future.

**Comment by LeoKlaus** [comment]
I've implemented a solution to this and will submit it to Apple right now. I expect the update to release in the coming 1-4 days.

**Comment by laipochen** [comment]
OK, I got it, thanks a lot!

**Comment by LeoKlaus** [comment]
Thank you again for the bug report and all the information.
